# Generated by Django 4.1.7 on 2023-05-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='marks',
            new_name='service',
        ),
    ]
